CREATE DATABASE IF NOT EXISTS CDW_SAPP;
USE CDW_SAPP;

set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;






--BRANCH

CREATE EXTERNAL TABLE IF NOT EXISTS TEMP_BRANCH 
				(BRANCH_CODE int, BRANCH_NAME varchar(25), 
				BRANCH_STREET varchar(30), BRANCH_CITY varchar(30), 
				BRANCH_STATE varchar(30), BRANCH_ZIP int, 
				BRANCH_PHONE varchar(12), LAST_UPDATED timestamp)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/user/maria_dev/Credit_Card_System/cdw_sapp_branch/';

CREATE EXTERNAL TABLE IF NOT EXISTS CDW_SAPP_D_BRANCH 
				(BRANCH_CODE int, BRANCH_NAME varchar(25), 
				BRANCH_STREET varchar(30), BRANCH_CITY varchar(30), 
				BRANCH_ZIP int, BRANCH_PHONE varchar(12), 
				LAST_UPDATED timestamp)
PARTITIONED BY (BRANCH_STATE varchar(30))
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/user/maria_dev/Credit_Card_System/Part/cdw_sapp_branch/';

INSERT OVERWRITE TABLE CDW_SAPP_D_BRANCH
PARTITION (BRANCH_STATE)
SELECT BRANCH_CODE, BRANCH_NAME, BRANCH_STREET, BRANCH_CITY, BRANCH_ZIP, BRANCH_PHONE, 
LAST_UPDATED, BRANCH_STATE
FROM TEMP_BRANCH;






--CREDITCARD

CREATE EXTERNAL TABLE IF NOT EXISTS TEMP_CREDITCARD 
					(TRANSACTION_ID bigint, CUST_CC_NO string, 
					TIMEID varchar(8), CUST_SSN int, BRANCH_CODE int, 
				    TRANSACTION_TYPE varchar(30), TRANSACTION_VALUE decimal(20, 3))
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/user/maria_dev/Credit_Card_System/cdw_sapp_creditcard/';

CREATE EXTERNAL TABLE IF NOT EXISTS CDW_SAPP_D_CREDITCARD 
					(TRANSACTION_ID bigint, CUST_CC_NO string, 
					TIMEID varchar(8), CUST_SSN int, BRANCH_CODE int, 
				    TRANSACTION_VALUE decimal(20, 3))
PARTITIONED BY (TRANSACTION_TYPE varchar(30))
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/user/maria_dev/Credit_Card_System/Part/cdw_sapp_creditcard/';

INSERT OVERWRITE TABLE CDW_SAPP_D_CREDITCARD
PARTITION (TRANSACTION_TYPE)
SELECT TRANSACTION_ID, CUST_CC_NO, TIMEID, CUST_SSN, BRANCH_CODE, TRANSACTION_VALUE,
TRANSACTION_TYPE
FROM TEMP_CREDITCARD;






--TIME

CREATE EXTERNAL TABLE IF NOT EXISTS TEMP_TIME 
				  (TIMEID varchar(8), DAY tinyint, MONTH tinyint,
			      QUARTER varchar(9), YEAR smallint, ID string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/user/maria_dev/Credit_Card_System/cdw_sapp_time/';

CREATE EXTERNAL TABLE IF NOT EXISTS CDW_SAPP_D_TIME 
					(TIMEID varchar(8), DAY tinyint, MONTH tinyint, YEAR smallint, ID string)
PARTITIONED BY (QUARTER varchar(9))
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/user/maria_dev/Credit_Card_System/Part/cdw_sapp_time/';

INSERT OVERWRITE TABLE CDW_SAPP_D_TIME
PARTITION (QUARTER)
SELECT TIMEID, DAY, MONTH, YEAR, ID, QUARTER
FROM TEMP_TIME;






--CUSTOMER

CREATE EXTERNAL TABLE IF NOT EXISTS TEMP_CUSTOMER 
    			  (CUST_SSN int, CUST_F_NAME varchar(40), CUST_M_NAME varchar(40),
				  CUST_L_NAME varchar(40), CUST_CC_NO string, CUST_STREET varchar(38), 
				  CUST_CITY varchar(30), CUST_STATE varchar(30), CUST_COUNTRY varchar(30),
				  CUST_ZIP int, CUST_PHONE varchar(8), CUST_EMAIL varchar(40),
				  LAST_UPDATED timestamp)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/user/maria_dev/Credit_Card_System/cdw_sapp_customer/';

CREATE EXTERNAL TABLE IF NOT EXISTS CDW_SAPP_D_CUSTOMER 
				  (CUST_SSN int, CUST_F_NAME varchar(40), CUST_M_NAME varchar(40),
				  CUST_L_NAME varchar(40), CUST_CC_NO string,
				  CUST_STREET varchar(38), CUST_CITY varchar(30),
				  CUST_COUNTRY varchar(30), CUST_ZIP int, CUST_PHONE varchar(8), 
				  CUST_EMAIL varchar(40), LAST_UPDATED timestamp)
PARTITIONED BY (CUST_STATE varchar(30))
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/user/maria_dev/Credit_Card_System/Part/cdw_sapp_customer/';

INSERT OVERWRITE TABLE CDW_SAPP_D_CUSTOMER
PARTITION (CUST_STATE)
SELECT CUST_SSN, CUST_F_NAME, CUST_M_NAME, CUST_L_NAME, CUST_CC_NO, CUST_STREET,
CUST_CITY, CUST_COUNTRY, CUST_ZIP, CUST_PHONE, CUST_EMAIL, LAST_UPDATED, CUST_STATE
FROM TEMP_CUSTOMER;